name: 'Mobile - Build and test'

on:
   push:
      paths: mobile/**
      branches: [feature/**, dev]      
   pull_request:
      paths: mobile/**
jobs:
   build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
         channel: 'stable' # or: 'dev' or 'beta'
    # Get flutter packages
    - name: 'pub get'
      working-directory: mobile
      run: flutter pub get
    # Build
    - name: 'build'
      working-directory: mobile
      run: flutter build aot
    #- name: 'analyze'
    #  working-directory: mobile
    #  run: flutter analyze --no-pub
    - name: 'test'
      if: always() && !cancelled()
      working-directory: mobile
      run: flutter test
